config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :business
  resources :categories
  resources :offers

  devise_for :users

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'businesses#show'
end

app/controllers/businesses_controller.rb
# frozen_string_literal: true

# Controller for managing businesses.
class BusinessesController < ApplicationController
  before_action :redirect_if_business_exists, only: %i[new create]
  before_action :set_business, only: %i[show edit update destroy]

  # GET `/business`.
  def show; end

  # GET `/business`.
  def new
    @business = current_user.build_business
  end

  # GET `/business`.
  def edit; end

  # POST `/business`.
  def create
    @business = current_user.build_business(business_params)

    if @business.save
      redirect_to business_path, notice: t('controllers.businesses.create.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT `/business`.
  def update
    if @business.update(business_params)
      redirect_to business_path, notice: t('controllers.businesses.update.success'), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE `/business`.
  def destroy
    @business.destroy!

    redirect_to new_business_path, notice: t('controllers.businesses.destroy.success'), status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_business
    @business = current_business
  end

  # Only allow a list of trusted parameters through.
  def business_params
    params.require(:business).permit(:name)
  end

  def redirect_if_business_exists
    return if current_user.business.blank?

    redirect_to business_path, alert: t('controllers.businesses.alerts.business_exists')
  end
end

app/helpers/businesses_helper.rb
# frozen_string_literal: true

# Module to provide helper methods for the businesses views.
module BusinessesHelper
end

app/views/businesses/_business.html.erb
<div id="<%= dom_id business %>">
  <p>
    <strong>User:</strong>
    <%= business.user_id %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= business.name %>
  </p>
</div>

app/views/businesses/_form.html.erb
<%= simple_form_for(@business, url: business_path) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :name %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/businesses/edit.html.erb
<h1>Editing business</h1>
<%= render "form", business: @business %>
<br>
<div>
  <%= link_to "Show business", business_path %>
</div>

app/views/businesses/new.html.erb
<h1>New business</h1>
<%= render "form", business: @business %>

app/views/businesses/show.html.erb
<%= render @business %>
<div>
  <%= link_to "Edit business", edit_business_path %>
  <%= link_to "Destroy business", business_path, data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %>
</div>