config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resource :business
  resources :categories
  resources :offers

  devise_for :users

  get 'up' => 'rails/health#show', as: :rails_health_check

  root 'businesses#show'
end

app/models/offer.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: offers
#
#  id                        :integer          not null, primary key
#  description               :text             default("")
#  discounted_price_cents    :integer          default(0), not null
#  discounted_price_currency :string           default("BRL"), not null
#  name                      :string           default(""), not null
#  original_price_cents      :integer          default(0), not null
#  original_price_currency   :string           default("BRL"), not null
#  visible                   :boolean          default(TRUE), not null
#  category_id               :integer          not null
#  created_at                :datetime         not null
#  updated_at                :datetime         not null
#
class Offer < ApplicationRecord
  db_belongs_to :category

  monetize :discounted_price_cents, numericality: true
  monetize :original_price_cents, numericality: { greater_than: 0 }

  validates :name, presence: true
  validates :category_id, db_uniqueness: true
end

app/controllers/offers_controller.rb
# frozen_string_literal: true

# Controller for managing offers.
class OffersController < ApplicationController
  before_action :set_offer, only: %i[show edit update destroy]

  # GET `/offers`.
  def index
    @offers = current_business.offers
  end

  # GET `/offers/1`.
  def show; end

  # GET `/offers/new`.
  def new
    @offer = current_business.offers.build
  end

  # GET `/offers/1/edit`.
  def edit; end

  # POST `/offers`.
  def create
    @offer = current_business.offers.build(offer_params)

    if @offer.save
      redirect_to @offer, notice: t('controllers.offers.create.success')
    else
      render :new, status: :unprocessable_entity
    end
  end

  # PATCH/PUT `/offers/1`.
  def update
    if @offer.update(offer_params)
      redirect_to @offer, notice: t('controllers.offers.update.success'), status: :see_other
    else
      render :edit, status: :unprocessable_entity
    end
  end

  # DELETE `/offers/1`.
  def destroy
    @offer.destroy!

    redirect_to offers_url, notice: t('controllers.offers.destroy.success'), status: :see_other
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_offer
    @offer = current_business.offers.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def offer_params
    params.require(:offer).permit(
      :description,
      :discounted_price,
      :name,
      :original_price,
      :visible,
      :category_id
    )
  end
end

app/helpers/offers_helper.rb
# frozen_string_literal: true

# Module to provide helper methods for the offers views.
module OffersHelper
end

app/views/offers/_form.html.erb
<%= simple_form_for(@offer) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>
  <div class="form-inputs">
    <%= f.input :description %>
    <%= f.input :discounted_price %>
    <%= f.input :name %>
    <%= f.input :original_price %>
    <%= f.input :visible %>
    <%= f.association :category %>
  </div>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/offers/_offer.html.erb
<div id="<%= dom_id offer %>">
  <p>
    <strong>Category:</strong>
    <%= offer.category_id %>
  </p>
  <p>
    <strong>Description:</strong>
    <%= offer.description %>
  </p>
  <p>
    <strong>Discounted price:</strong>
    <%= offer.discounted_price %>
  </p>
  <p>
    <strong>Name:</strong>
    <%= offer.name %>
  </p>
  <p>
    <strong>Original price:</strong>
    <%= offer.original_price %>
  </p>
  <p>
    <strong>Visible:</strong>
    <%= offer.visible %>
  </p>
</div>

app/views/offers/edit.html.erb
<h1>Editing offer</h1>
<%= render "form", offer: @offer %>
<br>
<div>
  <%= link_to "Show this offer", @offer %>
  <%= link_to "Back to offers", offers_path %>
</div>

app/views/offers/index.html.erb
<h1>Offers</h1>
<div id="offers">
  <% @offers.each do |offer| %>
    <%= render offer %>
    <p>
      <%= link_to "Show this offer", offer %>
    </p>
  <% end %>
</div>
<%= link_to "New offer", new_offer_path %>

app/views/offers/new.html.erb
<h1>New offer</h1>
<%= render "form", offer: @offer %>
<br>
<div>
  <%= link_to "Back to offers", offers_path %>
</div>

app/views/offers/show.html.erb
<%= render @offer %>
<div>
  <%= link_to "Edit this offer", edit_offer_path(@offer) %>
  <%= link_to "Back to offers", offers_path %>
  <%= link_to "Destroy this offer", @offer, data: { turbo_confirm: "Are you sure?", turbo_method: :delete } %>
</div>